### ISSUE TITLE
[Feature Request] Support collapsed level of menu

### ISSUE THREAD

**Issue by halfrost** [wowchemy/starter-book#1]
Is there any plan to support collapsed level of menu?

**Comment by gcushen** [comment]
Possibly, feel free to contribute a proposal at https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/layouts/partials/book_menu.html :)

Note that by changing the action of clicking chapter titles to expand/collapse their pages in the side bar, it could be a breaking change as then users cannot navigate to chapter pages and must create a separate "Intro" kind of page for each chapter.

**Comment by gcushen** [comment]
Tracked at https://github.com/wowchemy/wowchemy-hugo-modules/issues/1964
